//go:build ignore

// Gen writes the arity table for the go command in PATH to table.go.
package main

import (
	"bytes"
	"context"
	"fmt"
	"maps"
	"os"
	"slices"

	"lesiw.io/command"
	"lesiw.io/command/sys"
	"lesiw.io/fs"

	"lesiw.io/gorc/internal/arity"
)

var m = sys.Machine()

//ignore:linelen
const tmpl = `// Code generated by lesiw.io/gorc/internal/arity/gen; DO NOT EDIT.

package arity

// Table maps go command flags to whether the flag consumes the
// following word as its value when not written as -flag=value.
var Table = map[string]bool{
%s
}
`

func main() {
	if err := run(context.Background()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(ctx context.Context) error {
	table, err := arity.Load(ctx, m)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	for _, name := range slices.Sorted(maps.Keys(table)) {
		fmt.Fprintf(&buf, "\t%q: %v,\n", name, table[name])
	}
	err = fs.WriteFile(ctx, command.FS(m), "table.go", []byte(
		fmt.Appendf([]byte(nil), tmpl, buf.Bytes()),
	))
	if err != nil {
		return err
	}
	return command.Exec(ctx, m, "gofmt", "-w", "table.go")
}
